### PR TITLE
Adding new Music app

### PR DESCRIPTION
**Pull request by Benzamp**
Adding Music app to the Microhydra apps.

### CODE REVIEW

**Comment by Benzamp** [comment]
Hello!

I decided to focus on the Music app itself right now and figured it was in a good state for sharing!

**Comment by echo-lalia** [comment]
Cool, I'm exited to play around with it! Thanks for sharing 😁

**Comment by Benzamp** [comment]
> Cool, I'm exited to play around with it! Thanks for sharing 😁

Awesome!

When it comes to launching WAV files from the file explorer, I figured I could rework the code from the last PR to launch the this Music app then play them from there. I could work making this a built in app under `/launcher ` too if that makes WAV file support throughout more possible and easier.

**Comment by echo-lalia** [comment]
Yeah if you'd like to make the built-in file browser work with your music app, the app would probably have to be added as a built-in app alongside the others in `/launcher` :)

**Comment by echo-lalia** [comment]
Hello! I was working on getting all my apps updated to run on MicroHydra v2.0, and while I was at it, I made a couple of small changes to your `Music.py` to get it working on the newest (currently prerelease) version. I also extracted your icon from the docstring into an `icon.raw` file (which is the icon format for v2), in case you'd like to use that.

I hope that's alright with you!  
I'd prefer that everyone here feels a sense of ownership over the apps they make, and I don't wanna take that away with these changes :)

**Comment by Benzamp** [comment]
> Hello! I was working on getting all my apps updated to run on MicroHydra v2.0, and while I was at it, I made a couple of small changes to your `Music.py` to get it working on the newest (currently prerelease) version. I also extracted your icon from the docstring into an `icon.raw` file (which is the icon format for v2), in case you'd like to use that.
> 
> 
> 
> I hope that's alright with you!  
> 
> I'd prefer that everyone here feels a sense of ownership over the apps they make, and I don't wanna take that away with these changes :)

Sounds good! No issues on my end!

**Comment by Benzamp** [comment]
> Hello! I was working on getting all my apps updated to run on MicroHydra v2.0, and while I was at it, I made a couple of small changes to your `Music.py` to get it working on the newest (currently prerelease) version. I also extracted your icon from the docstring into an `icon.raw` file (which is the icon format for v2), in case you'd like to use that.
> 
> I hope that's alright with you! I'd prefer that everyone here feels a sense of ownership over the apps they make, and I don't wanna take that away with these changes :)

Hey! How do app icons work? I see you have it added in my app but not seeing it on the device, thanks!

**Comment by echo-lalia** [comment]
To use a custom icon, your app must be a folder with an icon inside. Like this:

Music/
├── Music/  
│ &nbsp; &nbsp; &nbsp; ├── icon.raw  
│ &nbsp; &nbsp; &nbsp; └── \_\_init\_\_.py    
└── details.yml  

> *In this example, `Music.py` has been renamed to `__init__.py`, which is the file Python looks for when you import a directory name. The `Music` directory (with the app script and the icon inside) is treated like an app.*

I was going through the repo and converting all the previous-version-style text-based icons into the new style of icon, and I decided to do yours too just for your convenience, but for whatever reason I decided not to move/rename your app into a folder (I guess just in case you preferred keeping it as a one file app). If you'd like the icon to work, you can just move/rename the files like I show above :)

**Comment by Benzamp** [comment]
Thanks! I got that squared away. Love the firmware by the way!

**Comment by echo-lalia** [comment]
Glad to hear it 😁

**Pull request merged**
